### ISSUE TITLE
df.json

### ISSUE THREAD

**Issue by yangdonbin** [2833844911/cyjsvmp#3]
你好，我看了一下你开源的项目，有几个不懂的问题，请教一下

1.我使用jiamian.js 加密后运行加密后的js,报如下错

![image](https://github.com/2833844911/cy_jsvmp/assets/75525530/5ff6542c-bdaf-419d-9f87-85b1893b4d58)

2.使用jiajianbian.js加密后可以运行，但df.json如何生成的，不太懂，替换成用jiamian.js  加密过程中生成的jiamain.json后，发现加密后的代码不可运行

求解  大神！！！

**Comment by 2833844911** [comment]
删除这行代码应该就可以了
